### ISSUE TITLE
WSFCFileServerPrivateIP parameter description correction

### ISSUE THREAD

**Issue by jrrudge** [aws-quickstart/quickstart-microsoft-sql#64]
The Fileserver parameter currently reads "Primary private IP for the file server located in Availability Zone 1"

However there is a condition that if ThirdAZ is set to witness it will use the 3rd Subnet and not the 1st. This will cause users to receive an error that he specified IP is invalid for the specified subnet if they specified the 1st.

```
  WSFCFileServerPrivateIP:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Default: 10.0.0.200
    Description: Primary private IP for the file server located in Availability Zone
      1.
    Type: String
```

```
  ThirdAZ:
    AllowedValues:
      - 'no'
      - witness
      - full
    Default: 'no'
    Description: Choose full or witness to enable a deployment with three Availability Zones. The third zone can be used for
      the witness, or it can be a full SQL cluster node.
    Type: String
```

```
  WSFCFileServer:
    Type: AWS::EC2::Instance
    Condition: IsTwoNode
    Properties:
      ImageId: !Ref WS2019FULLBASE
      IamInstanceProfile: !Ref 'WSFCProfile'
      InstanceType: !Ref 'WSFCFileServerInstanceType'
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: '0'
          SubnetId: !If
            - ThirdAzIsWitness
            - !Ref 'PrivateSubnet3ID'
            - !Ref 'PrivateSubnet1ID'
```
